env:
  es6: true
  node: true
  mocha: true
  es2020: true

root: true

parserOptions:
  sourceType: module

extends:
  - eslint:recommended
  - plugin:promise/recommended
  - plugin:node/recommended

rules:
  quotes: [ error, single, { avoidEscape: true, allowTemplateLiterals: true } ]
  no-unused-vars: [ error, { args: none } ]
  dot-notation: error
  prefer-const: warn
