import path from 'node:path'

/**
 * Nameserver config generators — the counterpart to the parseConfig / getZones
 * readers in bind.js, knot.js, maradns.js and nsd.js.
 *
 * Each takes the published zones and returns the text of the server's config
 * file, so a publisher can emit the zone data *and* tell the server about it.
 * Round-tripping a generated file back through the matching parser is the
 * contract these are tested against.
 *
 * `zones` is a Map of zone name -> zone file path, exactly the shape getZones
 * returns.
 */

const asEntries = (zones) =>
  zones instanceof Map ? [...zones.entries()] : Object.entries(zones ?? {})

/** A zone name with the root dot, which MaraDNS requires on its csv2 keys. */
const withRootDot = (name) => (name.endsWith('.') ? name : `${name}.`)

/**
 * Notify targets, as bare addresses. AxfrTransport accepts "host:port" so it
 * knows where to send; the config files below want the address on its own,
 * because the port belongs to a separate directive in each syntax.
 */
function notifyAddresses(notify) {
  const list = Array.isArray(notify) ? notify : notify ? [notify] : []
  return list
    .filter(Boolean)
    .map((t) => {
      if (typeof t === 'object') return t.address
      const str = String(t).trim()
      const bracketed = str.match(/^\[(.+)\](?::\d+)?$/)
      if (bracketed) return bracketed[1]
      // Split a trailing :port only when the rest is not itself IPv6.
      const parts = str.split(':')
      if (parts.length === 2 && /^\d+$/.test(parts[1])) return parts[0]
      return str
    })
    .filter(Boolean)
}

/**
 * BIND named.conf.
 *
 * @param {Map<string,string>} zones
 * @param {object} [opts]
 * @param {string} [opts.type='master']  zone type clause
 * @param {string} [opts.directory]      options { directory "..." }
 * @param {object} [opts.options]        further options{} statements, as
 *   key -> value; a value is emitted verbatim, so blocks like
 *   `{ 'listen-on port 5353': '{ 127.0.0.1; }' }` work
 * @param {boolean} [opts.relative=true] reference zone files by basename,
 *   which is how they resolve against `directory`
 * @param {string[]} [opts.notify]  secondaries to allow transfers to and to
 *   notify. Emitted per zone so a zone added later cannot inherit stale ACLs
 *   from a global block.
 */
export function toBindConfig(zones, opts = {}) {
  const { type = 'master', directory, options = {}, relative = true } = opts
  const out = ['// Generated by NicTool']
  const secondaries = notifyAddresses(opts.notify)

  const statements = []
  if (directory) statements.push(`directory "${directory}"`)
  for (const [k, v] of Object.entries(options)) statements.push(`${k} ${v}`)

  if (statements.length) {
    out.push('', 'options {', ...statements.map((x) => `  ${x};`), '};')
  }

  const addressList = (addrs) => `{ ${addrs.map((a) => `${a};`).join(' ')} }`

  for (const [name, file] of asEntries(zones)) {
    const target = relative ? path.basename(file) : file
    const block = [`zone "${name}" {`, `  type ${type};`, `  file "${target}";`]
    if (secondaries.length) {
      block.push(
        `  allow-transfer ${addressList(secondaries)};`,
        '  notify yes;',
        `  also-notify ${addressList(secondaries)};`,
      )
    }
    block.push('};')
    out.push('', ...block)
  }

  return out.join('\n') + '\n'
}

/**
 * NSD nsd.conf.
 *
 * @param {object} [opts.server] key/value pairs for the server: block
 * @param {string[]} [opts.notify]  secondaries to notify and provide-xfr to.
 *   NOKEY because TSIG is not wired up; NSD then authorizes by address.
 */
export function toNsdConfig(zones, opts = {}) {
  const out = ['# Generated by NicTool']
  const secondaries = notifyAddresses(opts.notify)

  if (opts.server && Object.keys(opts.server).length) {
    out.push('', 'server:')
    for (const [k, v] of Object.entries(opts.server)) out.push(`\t${k}: ${v}`)
  }

  for (const [name, file] of asEntries(zones)) {
    out.push('', 'zone:', `\tname: ${name}`, `\tzonefile: ${file}`)
    for (const addr of secondaries) {
      out.push(`\tnotify: ${addr} NOKEY`, `\tprovide-xfr: ${addr} NOKEY`)
    }
  }

  return out.join('\n') + '\n'
}

/**
 * Knot knot.conf. Zones are a YAML sequence, which the parser reads as
 * `- domain:` items.
 *
 * @param {object} [opts.server]   key/value pairs for the server: block
 * @param {string} [opts.storage]  template default storage directory
 * @param {string[]} [opts.notify]  secondaries. Knot names its peers in a
 *   `remote:` block and grants transfers through an `acl:`, so each address
 *   appears in three places and the zone references them by id.
 * @param {object} [opts.dnssec]  { algorithm, nsec3 } — Knot signs its own
 *   zones and manages the keys, so this declares a policy rather than handing
 *   it signed files.
 */
export function toKnotConfig(zones, opts = {}) {
  const out = ['# Generated by NicTool']
  const secondaries = notifyAddresses(opts.notify)
  const peerId = (i) => `nictool_secondary_${i + 1}`
  const dnssec = opts.dnssec ?? null

  if (opts.server && Object.keys(opts.server).length) {
    out.push('', 'server:')
    for (const [k, v] of Object.entries(opts.server)) out.push(`    ${k}: ${v}`)
  }

  if (secondaries.length) {
    out.push('', 'remote:')
    secondaries.forEach((addr, i) => {
      out.push(`  - id: ${peerId(i)}`, `    address: ${addr}`)
    })

    out.push('', 'acl:')
    secondaries.forEach((addr, i) => {
      out.push(`  - id: ${peerId(i)}_xfr`, `    address: ${addr}`, '    action: transfer')
    })
  }

  if (dnssec) {
    out.push(
      '',
      'policy:',
      '  - id: nictool_dnssec',
      `    algorithm: ${knotAlgorithm(dnssec.algorithm)}`,
      `    nsec3: ${dnssec.nsec3 ? 'on' : 'off'}`,
    )
  }

  if (opts.storage) {
    out.push('', 'template:', '  - id: default', `    storage: ${opts.storage}`)
  }

  const entries = asEntries(zones)
  if (entries.length) {
    out.push('', 'zone:')
    for (const [name, file] of entries) {
      out.push(`  - domain: ${name}`, `    file: ${file}`)
      if (dnssec) {
        out.push('    dnssec-signing: on', '    dnssec-policy: nictool_dnssec')
      }
      if (secondaries.length) {
        out.push(
          `    notify: [${secondaries.map((_, i) => peerId(i)).join(', ')}]`,
          `    acl: [${secondaries.map((_, i) => `${peerId(i)}_xfr`).join(', ')}]`,
        )
      }
    }
  }

  return out.join('\n') + '\n'
}

/**
 * Knot names algorithms in lowercase with dashes, where dnssec-keygen and the
 * API schema use BIND's spelling.
 */
const KNOT_ALGORITHMS = {
  RSASHA256: 'rsasha256',
  RSASHA512: 'rsasha512',
  ECDSAP256SHA256: 'ecdsap256sha256',
  ECDSAP384SHA384: 'ecdsap384sha384',
  ED25519: 'ed25519',
  ED448: 'ed448',
}

const knotAlgorithm = (algorithm) =>
  KNOT_ALGORITHMS[algorithm] ?? KNOT_ALGORITHMS.ECDSAP256SHA256

/**
 * CoreDNS Corefile, for the `file` plugin.
 *
 * One server block per zone rather than one block listing every zone: the
 * `file` plugin takes a single zone file, so a shared block would need every
 * zone in one file. Per-zone blocks also keep `transfer` scoped to its zone.
 *
 * @param {object} [opts]
 * @param {number} [opts.port]     appended to each block header
 * @param {string[]} [opts.notify] secondaries — becomes `transfer { to ... }`,
 *   which is both the AXFR ACL and the NOTIFY list in CoreDNS
 * @param {string} [opts.reload]   `file` plugin reload interval, e.g. '15s';
 *   CoreDNS polls the zone file, so this is how a published change is noticed
 * @param {string[]} [opts.plugins] extra directives added to every zone block
 * @param {boolean} [opts.relative=true] reference zone files by basename
 */
export function toCorefileConfig(zones, opts = {}) {
  const { port, reload, plugins = [], relative = true } = opts
  const secondaries = notifyAddresses(opts.notify)
  const out = ['# Generated by NicTool']

  for (const [name, file] of asEntries(zones)) {
    const target = relative ? path.basename(file) : file
    out.push('', `${name}${port ? `:${port}` : ''} {`)

    if (reload) {
      out.push(`    file ${target} {`, `        reload ${reload}`, '    }')
    } else {
      out.push(`    file ${target}`)
    }

    if (secondaries.length) {
      out.push('    transfer {', `        to ${secondaries.join(' ')}`, '    }')
    }
    for (const line of plugins) out.push(`    ${line}`)

    out.push('}')
  }

  return out.join('\n') + '\n'
}

/**
 * MaraDNS mararc.
 *
 * csv2 must be initialized before any zone is assigned into it, or MaraDNS
 * refuses to load them.
 *
 * @param {object} [opts.globals]  additional mararc variables
 * @param {string} [opts.chrootDir]
 * @param {string} [opts.bindAddress]
 */
export function toMaradnsConfig(zones, opts = {}) {
  const { chrootDir, bindAddress, globals = {} } = opts
  const out = ['# Generated by NicTool', '', 'csv2 = {}']

  for (const [name, file] of asEntries(zones)) {
    // Zone files are resolved inside chroot_dir, so reference the basename.
    out.push(`csv2["${withRootDot(name)}"] = "${path.basename(file)}"`)
  }

  const vars = { ...globals }
  if (bindAddress) vars.ipv4_bind_addresses = bindAddress
  if (chrootDir) vars.chroot_dir = chrootDir

  if (Object.keys(vars).length) {
    out.push('')
    for (const [k, v] of Object.entries(vars)) {
      out.push(typeof v === 'number' ? `${k} = ${v}` : `${k} = "${v}"`)
    }
  }

  return out.join('\n') + '\n'
}

const GENERATORS = {
  bind: toBindConfig,
  coredns: toCorefileConfig,
  knot: toKnotConfig,
  maradns: toMaradnsConfig,
  nsd: toNsdConfig,
}

/** Dispatch by nameserver type. Returns null for those with no config file. */
export function toNameserverConfig(format, zones, opts = {}) {
  const fn = GENERATORS[format]
  if (!fn) return null
  return fn(zones, opts)
}

export default {
  toBindConfig,
  toCorefileConfig,
  toKnotConfig,
  toMaradnsConfig,
  toNsdConfig,
  toNameserverConfig,
}
