import path from 'node:path'

/**
 * Nameserver config generators — the counterpart to the parseConfig / getZones
 * readers in bind.js, knot.js, maradns.js and nsd.js.
 *
 * Each takes the published zones and returns the text of the server's config
 * file, so a publisher can emit the zone data *and* tell the server about it.
 * Round-tripping a generated file back through the matching parser is the
 * contract these are tested against.
 *
 * `zones` is a Map of zone name -> zone file path, exactly the shape getZones
 * returns.
 */

const asEntries = (zones) =>
  zones instanceof Map ? [...zones.entries()] : Object.entries(zones ?? {})

/** A zone name with the root dot, which MaraDNS requires on its csv2 keys. */
const withRootDot = (name) => (name.endsWith('.') ? name : `${name}.`)

/**
 * BIND named.conf.
 *
 * @param {Map<string,string>} zones
 * @param {object} [opts]
 * @param {string} [opts.type='master']  zone type clause
 * @param {string} [opts.directory]      options { directory "..." }
 * @param {object} [opts.options]        further options{} statements, as
 *   key -> value; a value is emitted verbatim, so blocks like
 *   `{ 'listen-on port 5353': '{ 127.0.0.1; }' }` work
 * @param {boolean} [opts.relative=true] reference zone files by basename,
 *   which is how they resolve against `directory`
 */
export function toBindConfig(zones, opts = {}) {
  const { type = 'master', directory, options = {}, relative = true } = opts
  const out = ['// Generated by NicTool']

  const statements = []
  if (directory) statements.push(`directory "${directory}"`)
  for (const [k, v] of Object.entries(options)) statements.push(`${k} ${v}`)

  if (statements.length) {
    out.push('', 'options {', ...statements.map((x) => `  ${x};`), '};')
  }

  for (const [name, file] of asEntries(zones)) {
    const target = relative ? path.basename(file) : file
    out.push('', `zone "${name}" {`, `  type ${type};`, `  file "${target}";`, '};')
  }

  return out.join('\n') + '\n'
}

/**
 * NSD nsd.conf.
 *
 * @param {object} [opts.server] key/value pairs for the server: block
 */
export function toNsdConfig(zones, opts = {}) {
  const out = ['# Generated by NicTool']

  if (opts.server && Object.keys(opts.server).length) {
    out.push('', 'server:')
    for (const [k, v] of Object.entries(opts.server)) out.push(`\t${k}: ${v}`)
  }

  for (const [name, file] of asEntries(zones)) {
    out.push('', 'zone:', `\tname: ${name}`, `\tzonefile: ${file}`)
  }

  return out.join('\n') + '\n'
}

/**
 * Knot knot.conf. Zones are a YAML sequence, which the parser reads as
 * `- domain:` items.
 *
 * @param {object} [opts.server]   key/value pairs for the server: block
 * @param {string} [opts.storage]  template default storage directory
 */
export function toKnotConfig(zones, opts = {}) {
  const out = ['# Generated by NicTool']

  if (opts.server && Object.keys(opts.server).length) {
    out.push('', 'server:')
    for (const [k, v] of Object.entries(opts.server)) out.push(`    ${k}: ${v}`)
  }

  if (opts.storage) {
    out.push('', 'template:', '  - id: default', `    storage: ${opts.storage}`)
  }

  const entries = asEntries(zones)
  if (entries.length) {
    out.push('', 'zone:')
    for (const [name, file] of entries) {
      out.push(`  - domain: ${name}`, `    file: ${file}`)
    }
  }

  return out.join('\n') + '\n'
}

/**
 * MaraDNS mararc.
 *
 * csv2 must be initialized before any zone is assigned into it, or MaraDNS
 * refuses to load them.
 *
 * @param {object} [opts.globals]  additional mararc variables
 * @param {string} [opts.chrootDir]
 * @param {string} [opts.bindAddress]
 */
export function toMaradnsConfig(zones, opts = {}) {
  const { chrootDir, bindAddress, globals = {} } = opts
  const out = ['# Generated by NicTool', '', 'csv2 = {}']

  for (const [name, file] of asEntries(zones)) {
    // Zone files are resolved inside chroot_dir, so reference the basename.
    out.push(`csv2["${withRootDot(name)}"] = "${path.basename(file)}"`)
  }

  const vars = { ...globals }
  if (bindAddress) vars.ipv4_bind_addresses = bindAddress
  if (chrootDir) vars.chroot_dir = chrootDir

  if (Object.keys(vars).length) {
    out.push('')
    for (const [k, v] of Object.entries(vars)) {
      out.push(typeof v === 'number' ? `${k} = ${v}` : `${k} = "${v}"`)
    }
  }

  return out.join('\n') + '\n'
}

const GENERATORS = {
  bind: toBindConfig,
  knot: toKnotConfig,
  maradns: toMaradnsConfig,
  nsd: toNsdConfig,
}

/** Dispatch by engine name. Returns null for engines with no config file. */
export function toNameserverConfig(format, zones, opts = {}) {
  const fn = GENERATORS[format]
  if (!fn) return null
  return fn(zones, opts)
}

export default {
  toBindConfig,
  toKnotConfig,
  toMaradnsConfig,
  toNsdConfig,
  toNameserverConfig,
}
