import fs from 'node:fs/promises'
import path from 'node:path'

import { toMaraDNS } from '@nictool/dns-zone'

import { safeFileName } from '../zone-name.js'
import { zoneToRRs } from '../zone-rrs.js'

import { toMaradnsConfig } from '../config.js'
import Publisher from './base.js'

/**
 * MaradnsPublisher – writes MaraDNS csv2 zone files, and optionally the mararc
 * that declares them.
 *
 * MaraDNS does not read RFC 1035 zone files, so this is not a variant of
 * Rfc1035Publisher: csv2 is its own format, produced by the resource records'
 * own toMaraDNS().
 *
 * Artifacts shape:
 *   { kind, directory, files: Array<{ zone?: string, path: string }>, config: string|null }
 *
 * The mararc, when written, is a `files` entry with no `zone`.
 */
export class MaradnsPublisher extends Publisher {
  constructor(opts = {}) {
    super(opts)
    this.path = opts.path || './data/maradns'
    // MaraDNS 1.2's csv2 has no record terminator and rejects `~`; 2.x uses it.
    this.terminator = opts.terminator ?? '~'
    // When set, a mararc is written listing every zone; see toMaradnsConfig.
    this.config = opts.config ?? null
  }

  async publish(zones) {
    await fs.mkdir(this.path, { recursive: true })

    const files = []
    const declared = new Map()

    for (const [zoneName, { zone, records }] of zones) {
      // Validate the name before rendering, so a hostile one is refused as
      // such rather than surfacing as whatever the RR classes complain about.
      const target = path.join(
        this.path,
        `${safeFileName(zoneName, 'MaradnsPublisher')}.csv2`,
      )
      const text = renderZone(zoneName, zone, records, this.terminator)
      const tmp = target + '.tmp'
      await fs.writeFile(tmp, text)
      await fs.rename(tmp, target)

      files.push({ zone: zoneName, path: target })
      declared.set(zoneName, target)
    }

    let configPath = null
    if (this.config) {
      configPath = this.config.file ?? path.join(this.path, 'mararc')
      await fs.mkdir(path.dirname(configPath), { recursive: true })
      await fs.writeFile(
        configPath,
        toMaradnsConfig(declared, { chrootDir: this.path, ...this.config }),
      )
      files.push({ path: configPath })
    }

    const artifacts = { kind: 'maradns', directory: this.path, files, config: configPath }
    this.emit('published', artifacts)
    return artifacts
  }
}

function renderZone(zoneName, zone, records, terminator = '~') {
  const { rrs, apex, defaultTtl, errors } = zoneToRRs(zoneName, zone, records)
  const comments = errors.map((e) => `# ${e.owner} ${e.type}: ${e.message}`)

  const body = toMaraDNS(rrs, { origin: `${apex}.`, ttl: defaultTtl, terminator })
  return ['# Generated by NicTool', body.trimEnd(), ...comments].join('\n') + '\n'
}

export default MaradnsPublisher
