import fs from 'node:fs/promises'
import path from 'node:path'

import Publisher from './base.js'

/**
 * Rfc1035Publisher – writes RFC 1035 zone files to a directory.
 *
 * Artifacts shape:
 *   { directory: string, files: Array<{ zone: string, path: string }> }
 *
 * Transport implementations (rsync, db-replication) read `.directory` /
 * `.files` to know what to deliver. Zone files are named `<zone>.zone` and
 * safely replaced via write-to-tmp + rename.
 */
export class Rfc1035Publisher extends Publisher {
  constructor(opts = {}) {
    super(opts)
    this.path = opts.path || './data/zones-out'
  }

  async publish(zones) {
    await fs.mkdir(this.path, { recursive: true })
    const files = []
    for (const [zoneName, { zone, records }] of zones) {
      const text = renderZoneFile(zoneName, zone, records)
      const target = path.join(this.path, `${zoneName}.zone`)
      const tmp = target + '.tmp'
      await fs.writeFile(tmp, text)
      await fs.rename(tmp, target)
      files.push({ zone: zoneName, path: target })
    }
    return { directory: this.path, files }
  }
}

export default Rfc1035Publisher

function renderZoneFile(zoneName, zone, records) {
  const apex = zoneName.replace(/\.$/, '') + '.'
  const defaultTTL = Number(zone?.ttl ?? 3600)
  const lines = [
    `; Generated by NicTool`,
    `$ORIGIN ${apex}`,
    `$TTL ${defaultTTL}`,
    renderSOA(zone, apex, defaultTTL),
  ]

  for (const r of records) {
    if (r.deleted) continue
    if (String(r.type).toUpperCase() === 'SOA') continue // rendered above
    const line = renderRecord(r, apex, defaultTTL)
    if (line) lines.push(line)
  }

  return lines.join('\n') + '\n'
}

function renderSOA(zone, apex, defaultTTL) {
  const primary = fqdn(zone?.mailaddr ?? zone?.nsname ?? `ns1.${apex}`)
  const admin = fqdn(zone?.rname ?? `hostmaster.${apex}`)
  const serial = Number(zone?.serial ?? 1)
  const refresh = Number(zone?.refresh ?? 86400)
  const retry = Number(zone?.retry ?? 7200)
  const expire = Number(zone?.expire ?? 1209600)
  const minimum = Number(zone?.minimum ?? 3600)
  const ttl = Number(zone?.ttl ?? defaultTTL)
  return `@\t${ttl}\tIN\tSOA\t${primary} ${admin} ( ${serial} ${refresh} ${retry} ${expire} ${minimum} )`
}

function renderRecord(r, apex, defaultTTL) {
  const type = String(r.type ?? '').toUpperCase()
  const ttl = Number(r.ttl ?? defaultTTL)
  const owner = ownerLabel(r.name, apex)

  switch (type) {
    case 'A':
    case 'AAAA':
      return `${owner}\t${ttl}\tIN\t${type}\t${r.address}`
    case 'CNAME':
    case 'NS':
    case 'PTR':
    case 'DNAME':
      return `${owner}\t${ttl}\tIN\t${type}\t${fqdn(r.address)}`
    case 'MX':
      return `${owner}\t${ttl}\tIN\tMX\t${Number(r.weight ?? r.priority ?? 10)} ${fqdn(r.address)}`
    case 'TXT':
    case 'SPF':
      return `${owner}\t${ttl}\tIN\t${type}\t${quoteTxt(r.address)}`
    case 'SRV':
      return `${owner}\t${ttl}\tIN\tSRV\t${num(r.priority)} ${num(r.weight)} ${num(r.port)} ${fqdn(r.address)}`
    case 'CAA':
      return `${owner}\t${ttl}\tIN\tCAA\t${num(r.weight ?? 0)} ${r.tag ?? 'issue'} ${quoteTxt(r.address)}`
    default:
      return `; Unsupported type ${type} for ${owner}`
  }
}

function ownerLabel(name, apex) {
  const s = String(name ?? '').trim()
  if (!s || s === '@') return '@'
  if (s.endsWith('.')) return s
  return s // left relative to $ORIGIN
}

function fqdn(s) {
  const v = String(s ?? '').trim()
  if (!v) return '.'
  return v.endsWith('.') ? v : v + '.'
}

// RFC 1035 §5.1: backslash escapes the next character inside a quoted
// character-string, so it has to be doubled before the quotes are escaped.
// Escaping quotes alone leaves a trailing backslash swallowing the closing
// quote, emitting a malformed record.
function escapeTxt(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function quoteTxt(s) {
  const v = String(s ?? '')
  // Break strings longer than 255 chars per RFC 1035 / 4408. Chunking before
  // escaping is deliberate: escapes are presentation-only, so it is the
  // unescaped length that maps to the 255 byte wire limit.
  if (v.length <= 255) return `"${escapeTxt(v)}"`
  const parts = []
  for (let i = 0; i < v.length; i += 255) parts.push(v.slice(i, i + 255))
  return parts.map((p) => `"${escapeTxt(p)}"`).join(' ')
}

function num(v) {
  const n = Number(v)
  return Number.isFinite(n) ? n : 0
}
