import fs from 'node:fs/promises'
import path from 'node:path'

import { toBind } from '@nictool/dns-zone'

import { safeFileName } from '../zone-name.js'
import { zoneToRRs } from '../zone-rrs.js'

import { toNameserverConfig } from '../config.js'

import Publisher from './base.js'

/**
 * Rfc1035Publisher – writes RFC 1035 zone files to a directory.
 *
 * Artifacts shape:
 *   { directory: string, files: Array<{ zone: string, path: string }> }
 *
 * Transport implementations (rsync, db-replication) read `.directory` /
 * `.files` to know what to deliver. Zone files are named `<zone>.zone` and
 * safely replaced via write-to-tmp + rename.
 */
export class Rfc1035Publisher extends Publisher {
  constructor(opts = {}) {
    super(opts)
    this.path = opts.path || './data/zones-out'
    // { format: 'bind'|'knot'|'nsd', file, ...formatOpts } — when set, the
    // server's own config is written declaring every zone published here.
    this.config = opts.config ?? null
  }

  async publish(zones) {
    await fs.mkdir(this.path, { recursive: true })
    const files = []
    const declared = new Map()
    for (const [zoneName, { zone, records }] of zones) {
      // Validate the name before rendering, so a hostile one is refused as
      // such rather than surfacing as whatever the RR classes complain about.
      const target = path.join(
        this.path,
        `${safeFileName(zoneName, 'Rfc1035Publisher')}.zone`,
      )
      const text = renderZoneFile(zoneName, zone, records)
      const tmp = target + '.tmp'
      await fs.writeFile(tmp, text)
      await fs.rename(tmp, target)
      files.push({ zone: zoneName, path: target })
      declared.set(zoneName, target)
    }

    let configPath = null
    if (this.config?.format) {
      const text = toNameserverConfig(this.config.format, declared, {
        directory: this.path,
        ...this.config,
      })
      if (text) {
        configPath =
          this.config.file ?? path.join(this.path, defaultConfigName(this.config.format))
        await fs.mkdir(path.dirname(configPath), { recursive: true })
        await fs.writeFile(configPath, text)
        files.push({ path: configPath })
      }
    }

    const artifacts = { kind: 'rfc1035', directory: this.path, files, config: configPath }
    this.emit('published', artifacts)
    return artifacts
  }
}

export default Rfc1035Publisher

function renderZoneFile(zoneName, zone, records) {
  const { rrs, apex, defaultTtl, errors } = zoneToRRs(zoneName, zone, records)
  const comments = errors.map((e) => `; ${e.owner} ${e.type}: ${e.message}`)

  // hide.origin writes owners relative to $ORIGIN, as a zone file conventionally does.
  const body = toBind(rrs, {
    origin: `${apex}.`,
    ttl: defaultTtl,
    hide: { origin: true },
  })
  return ['; Generated by NicTool', body.trimEnd(), ...comments].join('\n') + '\n'
}

const CONFIG_NAMES = { bind: 'named.conf', knot: 'knot.conf', nsd: 'nsd.conf' }
const defaultConfigName = (format) => CONFIG_NAMES[format] ?? `${format}.conf`
