name: CI

on:
  push:

env:
  CI: true

jobs:
  lint:
    uses: NicTool/.github/.github/workflows/lint.yml@main

  coverage:
    uses: NicTool/.github/.github/workflows/coverage.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: NicTool/.github/.github/workflows/test.yml@main
    secrets: inherit