name: publish

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: NicTool/.github/.github/workflows/publish.yml@main
    secrets: inherit
